[toolchain]
targets = [

    # mac / local
    "aarch64-apple-darwin",

    # web
    "wasm32-unknown-unknown",

    # android
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "i686-linux-android",
    "x86_64-linux-android",

    # iOS
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",

]
